#!/usr/bin/python3

import os
import subprocess
import sys
import json
import multiprocessing
from functools import partial
from itertools import chain
import yaml
from generateBindings import generateCustomCodeBindings, _additionalBindCodeSymbols
from compileBindings import compileCustomCodeBindings, buildOneFile as compileOneBindingFile
from linkClosure import resolveClosure, indexBindings
import shutil
from cerberus import Validator
from argparse import ArgumentParser
from Common import ocIncludePaths, additionalIncludePaths
from buildPaths import OCJS_ROOT, numJobs

parser = ArgumentParser()
parser.add_argument(dest="filename", help="Custom build input file (.yml)", metavar="FILE.yml")
args = parser.parse_args()

libraryBasePath = OCJS_ROOT + "/build"

buildConfig = yaml.safe_load(open(args.filename, "r"))
schema = eval(open(OCJS_ROOT + "/src/customBuildSchema.py", "r").read())
v = Validator(schema)
if not v.validate(buildConfig, schema):
  raise Exception(v.errors)
buildConfig = v.normalized(buildConfig)

# Only delete custom code bindings (OCJS, Handle_IMeshTools_Context, etc.),
# not Handle/NCollection bindings generated by generateBindings.py
_customCodeDir = libraryBasePath + "/bindings/myMain.h"
if os.path.isdir(_customCodeDir):
  for _fname in os.listdir(_customCodeDir):
    # Keep Handle_ and NCollection-related bindings (generated by generateBindings.py)
    if (_fname.startswith("Handle_") or
        _fname.startswith("TColgp_") or _fname.startswith("TColStd_") or
        _fname.startswith("TopTools_") or _fname.startswith("Poly_Array") or
        _fname.startswith("NCollection_")):
      continue
    _fpath = os.path.join(_customCodeDir, _fname)
    if os.path.isfile(_fpath):
      os.remove(_fpath)

generateCustomCodeBindings(buildConfig["additionalCppCode"])
compileCustomCodeBindings({
  "threading": os.environ['threading'],
})

# ---------------------------------------------------------------------------
# Link-closure resolution: yml lists the API the consumer wants; base classes
# (required by Embind) and Handle_ types (optional, OCJS_INCLUDE_HANDLES=1)
# are pulled in automatically from the generated binding sources. Any closure
# symbol whose .cpp exists but whose .cpp.o was never compiled (e.g. when the
# compile-everything stage was skipped via OCJS_ONLY_SYMBOLS) is compiled here
# on demand, making single-yml builds incremental end to end.
# ---------------------------------------------------------------------------

def closureFor(bindings):
  """None means 'link everything' (empty bindings list, legacy behavior)."""
  requested = [b["symbol"] for b in bindings]
  if not requested:
    return None
  closure, missing = resolveClosure(
    requested, libraryBasePath + "/bindings",
    knownExternal=set(_additionalBindCodeSymbols))
  if missing:
    print(f"WARNING: no generated bindings for: {', '.join(sorted(missing))}")
  derived = closure - set(requested)
  if derived:
    print(f"Link closure added {len(derived)} symbols (bases/handles): {', '.join(sorted(derived))}")
  return closure

def ensureCompiled(closure):
  if closure is None:
    return
  idx = indexBindings(libraryBasePath + "/bindings")
  toCompile = [idx[s] for s in closure if s in idx and not os.path.exists(idx[s] + ".o")]
  if not toCompile:
    return
  print(f"Compiling {len(toCompile)} missing binding objects for link closure...")
  failedPaths = []
  compileArgs = {"threading": os.environ["threading"]}
  with multiprocessing.Pool(processes=numJobs()) as p:
    for status, path in p.imap_unordered(partial(compileOneBindingFile, compileArgs), sorted(toCompile)):
      if status == "failed":
        failedPaths.append(path)
        print("Warning: failed to compile " + path)
  if failedPaths:
    print(f"*** {len(failedPaths)} closure bindings failed to compile ***")

buildClosures = {}
buildClosures[buildConfig["mainBuild"]["name"]] = closureFor(buildConfig["mainBuild"]["bindings"])
for extraBuild in buildConfig["extraBuilds"]:
  buildClosures[extraBuild["name"]] = closureFor(extraBuild["bindings"])
for closure in buildClosures.values():
  ensureCompiled(closure)

def verifyBinding(binding) -> bool:
  for dirpath, dirnames, filenames in os.walk(libraryBasePath + "/bindings"):
    for item in filenames:
      if item.endswith(".cpp.o") and binding["symbol"] == item[:-6]:
        return True
  return False

def verifyBindings(bindings) -> list:
  missing = []
  for binding in bindings:
    if not verifyBinding(binding):
      print(f"WARNING: Requested binding {json.dumps(binding)} does not exist — will be missing from output!")
      missing.append(binding["symbol"])
  return missing

missingBindings = [s for s in verifyBindings(buildConfig["mainBuild"]["bindings"])
                   if s not in _additionalBindCodeSymbols]
for extraBuild in buildConfig["extraBuilds"]:
  missingBindings.extend(s for s in verifyBindings(extraBuild["bindings"])
                         if s not in _additionalBindCodeSymbols)
if missingBindings:
  print(f"\n*** {len(missingBindings)} bindings missing: {', '.join(missingBindings)} ***\n")
  if os.environ.get("OCJS_STRICT", "") == "1":
    print("OCJS_STRICT=1: aborting — see build/binding-compile-failures.txt for compile failures")
    sys.exit(1)

def shouldProcessSymbol(symbol: str, closure) -> bool:
  return closure is None or symbol in closure

def _dtsClosure():
  union = set()
  for closure in buildClosures.values():
    if closure is None:
      return None
    union |= closure
  return union

typescriptDefinitions = []
_dtsSet = _dtsClosure()
for dirpath, dirnames, filenames in os.walk(libraryBasePath + "/bindings"):
  for item in filenames:
    if item.endswith(".d.ts.json") and shouldProcessSymbol(item[:-10], _dtsSet):
      f = open(dirpath + "/" + item, "r")
      typescriptDefinitions.append(json.loads(f.read()))

def runBuild(build):
  def getAdditionalBindCodeO():
    if "additionalBindCode" in build:
      try:
        os.mkdir(libraryBasePath + "/additionalBindCode")
      except Exception:
        pass
      additionalBindCodeFileName = libraryBasePath + "/additionalBindCode/" + build["name"] + ".cpp"
      f = open(additionalBindCodeFileName, "w")
      f.write(build["additionalBindCode"])
      f.close()
      print("building " + additionalBindCodeFileName)
      command = [
        "emcc",
        "-std=c++17",
        "-flto",
        "-fexceptions",
        "-sDISABLE_EXCEPTION_CATCHING=0",
        "-DIGNORE_NO_ATOMICS=1",
        "-DOCCT_NO_PLUGINS",
        "-frtti",
        "-DHAVE_RAPIDJSON",
        "-Os",
        "-pthread" if os.environ["threading"] == "multi-threaded" else "",
        *list(map(lambda x: "-I" + x, ocIncludePaths + additionalIncludePaths)),
        "-c", additionalBindCodeFileName,
      ]
      subprocess.check_call([
        *command,
        "-o", additionalBindCodeFileName + ".o",
      ])
      return additionalBindCodeFileName + ".o"
    else:
      return None
  additionalBindCodeO = getAdditionalBindCodeO()
  print("Running build: " + build["name"])
  bindingsO = []
  for dirpath, dirnames, filenames in os.walk(libraryBasePath + "/bindings"):
    for item in filenames:
      if item.endswith(".cpp.o") and shouldProcessSymbol(item[:-6], buildClosures[build["name"]]):
        bindingsO.append(dirpath + "/" + item)
  sourcesO = []
  for dirpath, dirnames, filenames in os.walk(libraryBasePath + "/sources"):
    for item in filenames:
      if item in [
        "XBRepMesh.o",
      ]:
        continue
      if item.endswith(".o"):
        sourcesO.append(dirpath + "/" + item)
  subprocess.check_call([
    "emcc", "-lembind", ("" if additionalBindCodeO is None else additionalBindCodeO),
    *bindingsO, *sourcesO,
    "-o", os.getcwd() + "/" + build["name"],
    "-pthread" if os.environ["threading"] == "multi-threaded" else "",
    *build["emccFlags"],
  ])
  print("Build finished")

runBuild(buildConfig["mainBuild"])
for extraBuild in buildConfig["extraBuilds"]:
  runBuild(extraBuild)

if buildConfig["generateTypescriptDefinitions"]:
  typescriptDefinitionOutput = ""
  typescriptExports = []
  for dts in typescriptDefinitions:
    typescriptDefinitionOutput += dts[".d.ts"]
    for export in dts["exports"]:
      typescriptExports.append({
        "export": export,
        "kind": dts["kind"],
      })

  typescriptDefinitionOutput += \
    "type Standard_Boolean = boolean;\n" + \
    "type Standard_Byte = number;\n" + \
    "type Standard_Character = number;\n" + \
    "type Standard_CString = string;\n" + \
    "type Standard_Integer = number;\n" + \
    "type Standard_Real = number;\n" + \
    "type Standard_ShortReal = number;\n" + \
    "type Standard_Size = number;\n\n" + \
    "declare namespace FS {\n" + \
    "  interface Lookup {\n" + \
    "      path: string;\n" + \
    "      node: FSNode;\n" + \
    "  }\n" + \
    "\n" + \
    "  interface FSStream {}\n" + \
    "  interface FSNode {}\n" + \
    "  interface ErrnoError {}\n" + \
    "\n" + \
    "  let ignorePermissions: boolean;\n" + \
    "  let trackingDelegate: any;\n" + \
    "  let tracking: any;\n" + \
    "  let genericErrors: any;\n" + \
    "\n" + \
    "  //\n" + \
    "  // paths\n" + \
    "  //\n" + \
    "  function lookupPath(path: string, opts: any): Lookup;\n" + \
    "  function getPath(node: FSNode): string;\n" + \
    "\n" + \
    "  //\n" + \
    "  // nodes\n" + \
    "  //\n" + \
    "  function isFile(mode: number): boolean;\n" + \
    "  function isDir(mode: number): boolean;\n" + \
    "  function isLink(mode: number): boolean;\n" + \
    "  function isChrdev(mode: number): boolean;\n" + \
    "  function isBlkdev(mode: number): boolean;\n" + \
    "  function isFIFO(mode: number): boolean;\n" + \
    "  function isSocket(mode: number): boolean;\n" + \
    "\n" + \
    "  //\n" + \
    "  // devices\n" + \
    "  //\n" + \
    "  function major(dev: number): number;\n" + \
    "  function minor(dev: number): number;\n" + \
    "  function makedev(ma: number, mi: number): number;\n" + \
    "  function registerDevice(dev: number, ops: any): void;\n" + \
    "\n" + \
    "  //\n" + \
    "  // core\n" + \
    "  //\n" + \
    "  function syncfs(populate: boolean, callback: (e: any) => any): void;\n" + \
    "  function syncfs(callback: (e: any) => any, populate?: boolean): void;\n" + \
    "  function mount(type: any, opts: any, mountpoint: string): any;\n" + \
    "  function unmount(mountpoint: string): void;\n" + \
    "\n" + \
    "  function mkdir(path: string, mode?: number): any;\n" + \
    "  function mkdev(path: string, mode?: number, dev?: number): any;\n" + \
    "  function symlink(oldpath: string, newpath: string): any;\n" + \
    "  function rename(old_path: string, new_path: string): void;\n" + \
    "  function rmdir(path: string): void;\n" + \
    "  function readdir(path: string): any;\n" + \
    "  function unlink(path: string): void;\n" + \
    "  function readlink(path: string): string;\n" + \
    "  function stat(path: string, dontFollow?: boolean): any;\n" + \
    "  function lstat(path: string): any;\n" + \
    "  function chmod(path: string, mode: number, dontFollow?: boolean): void;\n" + \
    "  function lchmod(path: string, mode: number): void;\n" + \
    "  function fchmod(fd: number, mode: number): void;\n" + \
    "  function chown(path: string, uid: number, gid: number, dontFollow?: boolean): void;\n" + \
    "  function lchown(path: string, uid: number, gid: number): void;\n" + \
    "  function fchown(fd: number, uid: number, gid: number): void;\n" + \
    "  function truncate(path: string, len: number): void;\n" + \
    "  function ftruncate(fd: number, len: number): void;\n" + \
    "  function utime(path: string, atime: number, mtime: number): void;\n" + \
    "  function open(path: string, flags: string, mode?: number, fd_start?: number, fd_end?: number): FSStream;\n" + \
    "  function close(stream: FSStream): void;\n" + \
    "  function llseek(stream: FSStream, offset: number, whence: number): any;\n" + \
    "  function read(stream: FSStream, buffer: ArrayBufferView, offset: number, length: number, position?: number): number;\n" + \
    "  function write(\n" + \
    "      stream: FSStream,\n" + \
    "      buffer: ArrayBufferView,\n" + \
    "      offset: number,\n" + \
    "      length: number,\n" + \
    "      position?: number,\n" + \
    "      canOwn?: boolean,\n" + \
    "  ): number;\n" + \
    "  function allocate(stream: FSStream, offset: number, length: number): void;\n" + \
    "  function mmap(\n" + \
    "      stream: FSStream,\n" + \
    "      buffer: ArrayBufferView,\n" + \
    "      offset: number,\n" + \
    "      length: number,\n" + \
    "      position: number,\n" + \
    "      prot: number,\n" + \
    "      flags: number,\n" + \
    "  ): any;\n" + \
    "  function ioctl(stream: FSStream, cmd: any, arg: any): any;\n" + \
    "  function readFile(path: string, opts: { encoding: 'binary'; flags?: string }): Uint8Array;\n" + \
    "  function readFile(path: string, opts: { encoding: 'utf8'; flags?: string }): string;\n" + \
    "  function readFile(path: string, opts?: { flags?: string }): Uint8Array;\n" + \
    "  function writeFile(path: string, data: string | ArrayBufferView, opts?: { flags?: string }): void;\n" + \
    "\n" + \
    "  //\n" + \
    "  // module-level FS code\n" + \
    "  //\n" + \
    "  function cwd(): string;\n" + \
    "  function chdir(path: string): void;\n" + \
    "  function init(\n" + \
    "      input: null | (() => number | null),\n" + \
    "      output: null | ((c: number) => any),\n" + \
    "      error: null | ((c: number) => any),\n" + \
    "  ): void;\n" + \
    "\n" + \
    "  function createLazyFile(\n" + \
    "      parent: string | FSNode,\n" + \
    "      name: string,\n" + \
    "      url: string,\n" + \
    "      canRead: boolean,\n" + \
    "      canWrite: boolean,\n" + \
    "  ): FSNode;\n" + \
    "  function createPreloadedFile(\n" + \
    "      parent: string | FSNode,\n" + \
    "      name: string,\n" + \
    "      url: string,\n" + \
    "      canRead: boolean,\n" + \
    "      canWrite: boolean,\n" + \
    "      onload?: () => void,\n" + \
    "      onerror?: () => void,\n" + \
    "      dontCreateFile?: boolean,\n" + \
    "      canOwn?: boolean,\n" + \
    "  ): void;\n" + \
    "  function createDataFile(\n" + \
    "      parent: string | FSNode,\n" + \
    "      name: string,\n" + \
    "      data: ArrayBufferView | string,\n" + \
    "      canRead: boolean,\n" + \
    "      canWrite: boolean,\n" + \
    "      canOwn: boolean,\n" + \
    "  ): FSNode;\n" + \
    "  interface AnalysisResults {\n" + \
    "    isRoot: boolean,\n" + \
    "    exists: boolean,\n" + \
    "    error: Error,\n" + \
    "    name: string,\n" + \
    "    path: any,\n" + \
    "    object: any,\n" + \
    "    parentExists: boolean,\n" + \
    "    parentPath: any,\n" + \
    "    parentObject: any\n" + \
    "  }\n" + \
    "  function analyzePath(path: string): AnalysisResults;\n" + \
    "}\n\n" + \
    "\nexport type OpenCascadeInstance = {FS: typeof FS} & {\n  " + ";\n  ".join(map(lambda x: x["export"] + ((": typeof " + x["export"]) if x["kind"] == "class" else (": " + x["export"])), typescriptExports)) + ";\n" + \
    "};\n\n" + \
    "declare function init(): Promise<OpenCascadeInstance>;\n\n" + \
    "export default init;\n"

  typescriptDefinitionsFile = open(os.getcwd() + "/" + os.path.splitext(buildConfig["mainBuild"]["name"])[0] + ".d.ts", "w")
  typescriptDefinitionsFile.write(typescriptDefinitionOutput)
